const config = {
  PACKAGE_NAME: "@sha3/polymarket-snapshot",
  ALLOWED_SNAPSHOT_INTERVALS_MS: [100, 200, 500, 1000],
  DEFAULT_SNAPSHOT_INTERVAL_MS: 500,
  DEFAULT_SUPPORTED_ASSETS: ["btc", "eth", "sol", "xrp"],
  DEFAULT_SUPPORTED_WINDOWS: ["5m", "15m"],
  DEFAULT_PRICE_TO_BEAT_INITIAL_DELAY_MS: 10_000,
  DEFAULT_PRICE_TO_BEAT_RETRY_INTERVAL_MS: 5_000,
  MARKET_BOUNDARY_DELAY_MS: 250,
  MARKET_ACTIVATION_RETRY_INTERVAL_MS: 1_000,
} as const;

export default config;
